### ISSUE TITLE
Display causes crash on client side for empty contact lists.

### ISSUE THREAD

**Issue by StewartChandler** [CSC207-UofT/course-project-purplemongoose#52]
uhh, It's like I said.

**Comment by tiantian205** [comment]
fixed it. should be merged by ling/arthur soon-ish. meanwhile if you want to run the code without error you can use the following code in the method:
`            if(r[0].contains("[]")){
                return "Your contact list is empty!";
            }else {
                return String.format(" %s | %s | %s | %s | username: %s", (r[1]).split("\"")[0],
                        (r[5]).split("\"")[0], (r[3]).split("\"")[0],
                        (r[2]).split("\"")[0], (r[4]).split("\"")[0]);
            }`
